version: '3.3'

networks:
  default:
    external:
      name: network_default

services:

  phpmyadmin:
    container_name: php.admin
    image: phpmyadmin/phpmyadmin
    environment:
    - VIRTUAL_HOST=pma.${DOMAIN}
    - LETSENCRYPT_HOST=pma.${DOMAIN}
    - LETSENCRYPT_EMAIL=${USER_EMAIL}
    - PMA_ARBITRARY=1
    restart: always
    expose:
    - 80
    volumes:
    - /sessions
    labels:
    - com.centurylinklabs.watchtower.enable='true'
