version: '3.3'

networks:
  default:
    external:
      name: network_default

volumes:
  mautic-web:
  mautic-db:

services:

  mautic:
    container_name: llt.mautic
    hostname: mautic.${DOMAIN}
    restart: unless-stopped
    image: mautic/mautic:v3
    expose:
    - 80
    - 443
    environment:
      LETSENCRYPT_HOST: mautic.${DOMAIN}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      VIRTUAL_HOST: mautic.${DOMAIN}
      VIRTUAL_HOST_NAME: "mautic"
      MAUTIC_DB_HOST: mariadb
      MAUTIC_DB_USER: ${USER_NAME}
      MAUTIC_DB_PASSWORD: ${USER_PASSWORD}
    volumes:
    - mautic-web:/var/www/html