version: '3.3'

networks:
  default:
    external:
      name: network_default
      
volumes:
  wordpress_html:
  wordpress_data:

services:

  db:
    container_name: $DB_CONTAINER
    image: mariadb:latest
    restart: always
    expose: 
    - 3306
    volumes:
    - wordpress_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    - MYSQL_DATABASE=${NAME}
    - MYSQL_USER=${USER_NAME}
    - MYSQL_PASSWORD=${USER_PASSWORD}

  wp:
    container_name: $WP_CONTAINER
    image: wordpress
    depends_on:
    - db
    # - cp
    restart: always
    expose:
    - 80
    - 433
    volumes:
    - ./theme:/var/www/html/wp-content/themes/${WP_THEME}:rw
    - ./plugin:/var/www/html/wp-content/plugins/${WP_PLUGIN}:rw
    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    - wordpress_html:/var/www/html
    environment:  
    - WORDPRESS_DB_HOST=$DB_CONTAINER
    - WORDPRESS_DB_NAME=${NAME}
    - WORDPRESS_DB_USER=${USER_NAME}
    - WORDPRESS_DB_PASSWORD=${USER_PASSWORD}
    - VIRTUAL_HOST=${DOMAIN}
    - LETSENCRYPT_HOST=${DOMAIN}
    - LETSENCRYPT_EMAIL=${USER_EMAIL}

  # cp:
  #   container_name: ${COMPOSER_CONTAINER}
  #   build: composer    
  #   volumes:
  #   - /var/lib/docker/volumes/${NAME}_wordpress_html/_data/wp-content:/app/wp-content
  #   command: composer install
